export const data = [
{name:"Meghana-food",rating:3.8,cuisines:"Biryani Andhra South Indian"},
{name:"KFC",rating:4.2,cuisines:"Chicken leg , burger etc"},
{name:"Radhe bakers",rating:3,cuisines:"Kur-kure, pepsi , Allen girls"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
{name:"Meghana-food",rating:4.2,cuisines:"Biryani Andhra South Indian"},
]